In [37]:
import pandas as pd

In [38]:
df = pd.read_csv('/content/drive/MyDrive/Datasets/train.csv')
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [39]:
df.shape

(20800, 5)

In [40]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [41]:
df = df.dropna()

In [42]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [43]:
X = df.drop('label',axis=1)

In [44]:
y = df['label']

In [45]:
X.shape

(18285, 4)

In [46]:
y.shape

(18285,)

In [47]:
import tensorflow as tf

In [48]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [49]:
## vocabulary size
vocab_size = 5000

In [59]:
# ONEHOT REPRESENTATION

In [63]:
messages = X.copy()

In [66]:
messages.reset_index(inplace=True)

In [67]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [68]:
messages

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [69]:
import nltk
import re
from nltk.corpus import stopwords

In [70]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [71]:
## data preprocessing
from nltk.stem.porter import PorterStemmer

In [72]:
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [73]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [74]:
corpus[2]

'truth might get fire'

In [75]:
onehot_repr = [one_hot(words,vocab_size) for words in corpus]
onehot_repr

[[292, 2677, 4269, 3945, 2446, 4177, 743, 3734, 4156, 4346],
 [1906, 1328, 2459, 2573, 3898, 153, 223],
 [4461, 2888, 3825, 2259],
 [2192, 3224, 393, 2469, 2050, 3843],
 [3120, 3898, 1861, 1204, 2779, 1454, 3898, 2582, 1195, 1154],
 [3702,
  4593,
  57,
  1713,
  3337,
  1287,
  2509,
  465,
  2877,
  1526,
  430,
  25,
  176,
  4511,
  223],
 [3703, 4437, 3427, 998, 1780, 2239, 4392, 4009, 3935, 2413, 3736],
 [3547, 794, 2208, 3559, 1118, 2673, 1287, 373, 3935, 2413, 3736],
 [444, 3681, 3758, 512, 595, 801, 480, 4803, 1287, 557],
 [1245, 1964, 4508, 4368, 2198, 4329, 4557, 3591],
 [1370, 3779, 4839, 4904, 2425, 4308, 2724, 1849, 818, 3144, 4168],
 [2469, 4934, 2446, 801, 1287, 1118],
 [1590, 4727, 2602, 2246, 3221, 1255, 1537, 4219, 222],
 [53, 875, 1415, 1315, 2853, 3860, 3910, 3935, 2413, 3736],
 [3903, 1912, 836, 3454, 1056, 3935, 2413, 3736],
 [3587, 4212, 4225, 3367, 4451, 4197, 3102, 3333, 4138, 1285],
 [159, 129, 1328],
 [3863, 3405, 1680, 1773, 1287, 2212, 4214, 223],
 [2391, 

In [77]:
# EMBEDDIG REPRENTATION

sent_length = 20
embedded_docs = pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[ 292 2677 4269 ...    0    0    0]
 [1906 1328 2459 ...    0    0    0]
 [4461 2888 3825 ...    0    0    0]
 ...
 [3679  685  292 ...    0    0    0]
 [1567 1118 1902 ...    0    0    0]
 [ 568 4932  613 ...    0    0    0]]


In [78]:
embedded_docs[1]

array([1906, 1328, 2459, 2573, 3898,  153,  223,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [79]:
# Building Model

embedded_vector_features = 40

model = Sequential()

model.add(Embedding(vocab_size,embedded_vector_features,input_length = sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [80]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [81]:
len(embedded_docs),y.shape

(18285, (18285,))

In [82]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [83]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [84]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [85]:
### Finally model Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 18s 66ms/step - loss: 0.3072 - accuracy: 0.8519 - val_loss: 0.1943 - val_accuracy: 0.9178
Epoch 2/10
192/192 [==============================] - 5s 24ms/step - loss: 0.1362 - accuracy: 0.9480 - val_loss: 0.1999 - val_accuracy: 0.9190
Epoch 3/10
192/192 [==============================] - 2s 10ms/step - loss: 0.0904 - accuracy: 0.9669 - val_loss: 0.2119 - val_accuracy: 0.9195
Epoch 4/10
192/192 [==============================] - 2s 9ms/step - loss: 0.0561 - accuracy: 0.9815 - val_loss: 0.2930 - val_accuracy: 0.9153
Epoch 5/10
192/192 [==============================] - 2s 10ms/step - loss: 0.0395 - accuracy: 0.9882 - val_loss: 0.2920 - val_accuracy: 0.9143
Epoch 6/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0298 - accuracy: 0.9917 - val_loss: 0.3223 - val_accuracy: 0.9155
Epoch 7/10
192/192 [==============================] - 2s 12ms/step - loss: 0.0213 - accuracy: 0.9940 - val_loss: 0.4598 - val_accuracy: 0.9107
